version: '3.4'
services:
  # postgres:
  #   image: postgres:14-alpine
  #   environment:
  #     POSTGRES_USER: db_eventos
  #     POSTGRES_PASSWORD: KKJH8969KJH7869
  #     POSTGRES_DB: baston_eventos
  #     PGDATA: /data/postgres
  #   volumes:
  #      - postgres:/data/postgres
  #   ports:
  #     - 5432:5432
  #   networks:
  #     - baston_eventos
  #   restart: unless-stopped
  
  baston_eventos:
    image: golang:1.15-alpine
    working_dir: /app
    command: sh deployment/dev.sh
    volumes:
      - ..:/app
    ports: 
      - 8080:8080
    env_file:
      - ../.envs/.local/.env
    restart: unless-stopped
    networks: 
      - baston_eventos

networks:
  baston_eventos:
    external: true

volumes:
    postgres: