version: '3.4'
services:
  eventos:
    image: golang:1.16-alpine
    working_dir: /app
    command: sh deployment/dev.sh
    volumes:
      - ..:/app
      - ~/.ssh/id_ed25519:/root/.ssh/id_rsa
    ports: 
      - 8089:8089
    env_file:
      - ../.envs/.local/.env
    restart: unless-stopped
    networks: 
      - bastos

networks:
  bastos:
    external: true

volumes:
    postgres: