# Deps stage
FROM golang:1.16-alpine  AS deps
ARG ssh_prv_key
RUN apk --no-cache add tzdata git openssh
RUN go env -w GOPRIVATE=github.com/nilsyadv/*
RUN mkdir /root/.ssh
RUN echo "StrictHostKeyChecking no " > /root/.ssh/config
RUN printf "[url \"git@github.com:\"]\n\tinsteadOf = https://github.com/" >> /root/.gitconfig
RUN echo "$ssh_prv_key" > /root/.ssh/id_ed25519 && \
    chmod 600 /root/.ssh/id_ed25519
ADD go.mod /app/go.mod
ADD go.sum /app/go.sum
WORKDIR /app
RUN go mod download

# Build stage
FROM golang:1.16-alpine AS builder
ADD . /app
COPY --from=deps /go /go
WORKDIR /app
RUN mkdir /build
RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o /build/main /app/cmd/main.go
RUN ls -la /build

# Final stage
FROM alpine:latest
RUN apk --no-cache add  curl ca-certificates tzdata
COPY --from=builder /app/config /config
COPY --from=builder /app/deployment /app/deployment
COPY --from=builder /build /app
RUN chmod +x /app/main
ENTRYPOINT ["/app/main"]
EXPOSE 8089